#!/bin/sh

alias L1='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.1.1'
alias L2='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.1.2'
alias L4='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.1.4'
alias S21='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.2.21'
alias S22='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.2.22'
alias BL31='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.31'
alias BL32='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.32'
alias SRV1='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.1'
alias SRV5='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.5'
alias SRV7='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.7'
alias RBL33='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.33'
alias RBL34='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.34'
alias RS41='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.41'
alias RS42='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.42'
alias RL51='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.51'
alias RL52='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.52'
alias RSRV1='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.1'
alias RBL35='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.35'
alias RBL36='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.36'
alias RS43='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.43'
alias RS44='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.44'
alias RL53='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.53'
alias RL54='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.54'
alias RSRV3='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.3'
alias RSRV2='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.2'
alias L3Provider='sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.200'
