#!/bin/sh
tmux new-session -s Lab -d
tmux new-window -t Lab:1 -n L1 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.1.1'
tmux new-window -t Lab:2 -n L2 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.1.2'
tmux new-window -t Lab:3 -n L4 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.1.4'
tmux new-window -t Lab:4 -n S21 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.2.21'
tmux new-window -t Lab:5 -n S22 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.2.22'
tmux new-window -t Lab:6 -n BL31 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.31'
tmux new-window -t Lab:7 -n BL32 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.32'
tmux new-window -t Lab:8 -n SRV1 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.1'
tmux new-window -t Lab:9 -n SRV5 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.5'
tmux new-window -t Lab:10 -n SRV7 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.7'
tmux new-window -t Lab:11 -n RBL33 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.33'
tmux new-window -t Lab:12 -n RBL34 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.34'
tmux new-window -t Lab:13 -n RS41 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.41'
tmux new-window -t Lab:14 -n RS42 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.42'
tmux new-window -t Lab:15 -n RL51 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.51'
tmux new-window -t Lab:16 -n RL52 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.52'
tmux new-window -t Lab:17 -n RSRV1 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.1'
tmux new-window -t Lab:18 -n RBL35 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.35'
tmux new-window -t Lab:19 -n RBL36 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.36'
tmux new-window -t Lab:20 -n RS43 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.43'
tmux new-window -t Lab:21 -n RS44 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.44'
tmux new-window -t Lab:22 -n RL53 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.53'
tmux new-window -t Lab:23 -n RL54 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.3.54'
tmux new-window -t Lab:24 -n RSRV3 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.3'
tmux new-window -t Lab:25 -n RSRV2 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.2'
tmux new-window -t Lab:26 -n L3Provider 'sshpass -p cisco ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no cisco@172.16.5.200'
